s=set()
s.add(10)
print(s)
print(type(s))
#s.add(10,20,30)
#print(s) #TypeError:add()takes exactly one argument(3 given)
#s.update(10) #TypeError:'int' object is not iterable
#print(s)
s.update(range(1,10,2),range(0,10,2))
print(s)
print(type(s))
